import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '../styles/Content.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tomtropolis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sunlogo.ico" />        
      </Head>

      <main>

        <Navbar />

        <div className={styles.container}>

              <p>
                  Currently, a Software Developer at{' '}
                  <a href="https://environicsanalytics.com/">Environics Analytics</a> in Toronto where I&rsquo;m
                  working on our backend, building new APIs with .NET Core, and doing some cloud/big data work.
              </p>
              <p>
                  Previously co-founded a data science conference+workshop company called{' '}
                  <a href="https://thomaslillo.github.io/datathon-website-tailwindcss/">Datathon Analytics Events</a>, teaching students to code and connecting them with industry. See an article about it <a href="https://brocku.ca/brock-news/tag/datathon/">here</a>.
              </p>
              <p>
                  In my free time I work on <a href="https://wovenmining.ca">Woven Mining</a>, where I used
                  machine learning to turn data and documents into insights for the metal mining industry
              </p>
              <h4>Things I Like:</h4>
              <p>
                  {' '}
                  - Spatial data science, I&rsquo;m an award-winning map maker, getting into the{' '}
                  <a href="https://map-calendar-esricanada.hub.arcgis.com/pages/aug-2021">ESRI calendar</a> and
                  map book
              </p>
              
              <p> - Building systems that solve problems with technology, like I did to <a href='https://twitter.com/AgritechH/status/1325538033203097600?s=20'>win a MLH Hackathon in 2020</a>, and the <a href='https://www.youtube.com/watch?v=zT_Cz_2kpuM&embeds_euri=https%3A%2F%2Fagritechhackathon.ca%2F&source_ve_path=MjM4NTE&feature=emb_title'>pre-hackathon challenge</a>, providing <a href='https://www.youtube.com/watch?v=SWMlrud_z6g'>practical solutions</a> to problems.</p>
              <p>
                  contact me ={' '}
                  <a href="mailto:thomas.j.lillo@gmail.com">thomas.j.lillo at gmail</a>, or for my business{' '}
                  <a href="mailto:thomas@wovenmining.ca">thomas at wovenmining.ca</a>
              </p>
              <br />              
          </div>

          <Footer />
      </main>
    </div>
  )
}
